-- =====================================================================
-- EyeCanHelp Buddy — PostgreSQL schema
--
-- Idempotent: re-running on a populated database is safe (CREATE TABLE
-- IF NOT EXISTS).
--
-- Run with:
--     psql -h <host> -U <user> -d <db> -v ON_ERROR_STOP=1 \
--          -f 01_postgres_schema.sql
--
-- Mirrors SQLAlchemy DeclarativeBase metadata from backend/models/*.py.
-- Column names match SQLAlchemy's output verbatim, including the mixed-
-- case identifiers (which Postgres folds to lowercase unless quoted, so
-- they MUST be quoted in DDL and INSERTs).
-- =====================================================================

-- TBL_PATIENT — FHIR R4 Patient. Demographics master.
CREATE TABLE IF NOT EXISTS "TBL_PATIENT" (
    patient_id   VARCHAR(50)  PRIMARY KEY,
    patient_name VARCHAR(255) NOT NULL,
    patient_dob  VARCHAR(20)  NOT NULL,  -- ISO date string
    phone_number VARCHAR(20)
);

-- TBL_IVT — FHIR R4 MedicationRequest/Procedure. Catalogue of IVT meds.
CREATE TABLE IF NOT EXISTS "TBL_IVT" (
    ivt_id         VARCHAR(50)  PRIMARY KEY,
    ivt_name       VARCHAR(255) NOT NULL,
    ivt_eyes       VARCHAR(10)  NOT NULL,  -- OD | OS | OU
    ivt_medication VARCHAR(255) NOT NULL
);

-- TBL_CHAT_EXCHANGE_LOG — General enquiry chat transcript rows.
-- Stores one row per user prompt and assistant response pair.
CREATE TABLE IF NOT EXISTS "TBL_CHAT_EXCHANGE_LOG" (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      VARCHAR(100)     NOT NULL,
    mode            VARCHAR(50)      NOT NULL,
    user_message    TEXT             NOT NULL,
    system_response TEXT             NOT NULL,
    created_at      TIMESTAMP        NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Singapore')
);

CREATE INDEX IF NOT EXISTS idx_tbl_chat_exchange_log_session
    ON "TBL_CHAT_EXCHANGE_LOG" (session_id);
